# Generated by Django 4.1.1 on 2022-09-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('D', 'Delivered'), ('P', 'Pending'), ('C', 'Cancelled')], default='P', max_length=1, null=True),
        ),
    ]
